name: publish
on: 
  push:
    branches: ['main']
jobs:
  publish:
    name: Push Docker image 
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the hello-docker Docker image
      run: |
        docker build . --tag ghcr.io/rare-freertr/freertr:clab
        docker run ghcr.io/rare-freertr/freertr:clab
        docker push ghcr.io/rare-freertr/freertr:clab
